# Generated by Django 4.2.6 on 2023-11-24 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="clocked_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
