# Generated by Django 4.2.6 on 2023-11-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_record_clocked_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="clocked_time",
            field=models.DateTimeField(),
        ),
    ]
