# Generated by Django 4.2.6 on 2023-11-24 13:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_alter_record_clocked_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="clocked_time",
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
