# Generated by Django 4.2.6 on 2023-11-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0006_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="em_id",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="em_id",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
