# Generated by Django 4.2.6 on 2023-11-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0007_alter_employee_em_id_alter_record_em_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="clocking_type",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="record",
            name="remark",
            field=models.CharField(default=False, max_length=250),
            preserve_default=False,
        ),
    ]
