# Generated by Django 4.2.6 on 2023-11-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0008_record_clocking_type_record_remark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="remark",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
