# Generated by Django 4.2.6 on 2023-11-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0010_alter_record_em_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("em_id", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=150)),
                ("role", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("remark", models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name="record",
            name="remark",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
