# Generated by Django 4.2.6 on 2023-11-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0011_employeerecord_alter_record_remark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeerecord",
            name="remark",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
