# Generated by Django 4.2.6 on 2023-11-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0012_alter_employeerecord_remark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeerecord",
            name="remark",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name="record",
            name="remark",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
