# Generated by Django 4.2.7 on 2023-11-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0013_alter_employeerecord_remark_alter_record_remark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="em_id",
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
