# Generated by Django 4.2.7 on 2023-11-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0015_fileupload_alter_employee_em_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileupload",
            name="column1",
            field=models.FileField(upload_to="load_to_db/"),
        ),
    ]
