# Generated by Django 4.2.7 on 2023-11-28 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0016_alter_fileupload_column1"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fileupload",
            old_name="column1",
            new_name="file",
        ),
        migrations.RemoveField(
            model_name="fileupload",
            name="column2",
        ),
    ]
