# Generated by Django 4.2.7 on 2023-11-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0017_rename_column1_fileupload_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileupload",
            name="file",
            field=models.FileField(upload_to="load_to_db"),
        ),
    ]
